### ISSUE TITLE
Guide to use with Fastify adapter?

### ISSUE THREAD

**Issue by r-priyam** [SocketSomeone/necord#82]
### What is your question?

Looking for a guide that how to set this up with NestJs using Fastify. The simple configuration as mentioned in docs doesn't seem to work and raising errors.

```
C:\Users\Priyam\Documents\api-next\node_modules\@nestjs\platform-fastify\adapters\fastify-adapter.js:242
        return !('status' in response);
                          ^

TypeError: Cannot use 'in' operator to search for 'status' in undefined
    at FastifyAdapter.isNativeResponse (C:\Users\Priyam\Documents\api-next\node_modules\@nestjs\platform-fastify\adapters\fastify-adapter.js:242:27)
    at FastifyAdapter.reply (C:\Users\Priyam\Documents\api-next\node_modules\@nestjs\platform-fastify\adapters\fastify-adapter.js:117:35)
    at ExceptionsFilter.catch (C:\Users\Priyam\Documents\api-next\dist\main.js:844:21)
    at ExternalExceptionsHandler.invokeCustomFilters (C:\Users\Priyam\Documents\api-next\node_modules\@nestjs\core\exceptions\external-exceptions-handler.js:34:32)
    at ExternalExceptionsHandler.next (C:\Users\Priyam\Documents\api-next\node_modules\@nestjs\core\exceptions\external-exceptions-handler.js:13:29)
    at Object.execute (C:\Users\Priyam\Documents\api-next\node_modules\@nestjs\core\helpers\external-proxy.js:14:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.1.0
```

**Comment by SocketSomeone** [comment]
Hey there, can you give me a minimal repository for reproducing your error?

**Comment by r-priyam** [comment]
> Hey there, can you give me a minimal repository for reproducing your error?

Before I do, I just want to know that, does it will work when I am doing like this in my `main.ts` and for config it's as same as mentioned in wiki

```ts
async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());
  await app.listen(3000);
}
bootstrap();
```

If yes, then I guess I am not doing anything wrong and I will provide the repro.

**Comment by SocketSomeone** [comment]
I think you are doing everything right.
[Read more about Fastify + Nest.js](https://docs.nestjs.com/techniques/performance)

But I have some doubt about how you are using Necord. I must say right away that Necord uses [Discord.js](https://discord.js.org/#/) as the core for working with Discord and does not support receiving [interactions via HTTP (Webhook)](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-interaction-callback-data-flags).

**Comment by r-priyam** [comment]
Just created a scratch project and it's working fine, probably I myself messed up somewhere. I will try to dig in and will inform you if I find anything buggy, Thank you! Will close this issue
